---
# tasks file for vsftpd

- name: Install package
  package:
    name: vsftpd
    state: present

- name: Configure vsftpd
  template:   
    src: vsftpd.conf.j2 
    dest: /etc/vsftpd/vsftpd.conf 
    mode: 0600 
    backup: yes

- name: Start and ensure the vsftpd service starts at boot
  systemd:
    name: vsftpd
    state: started
    enabled: True